/*
 * Option texts of the questionnaire's three dropdowns, exactly as the
 * console shows them (docs/dom-map.md, "Dropdowns"). Used by the options
 * page to offer a <select> per field; the stored setting stays the plain
 * option text, so the content script is unchanged. A list that is empty
 * makes the options page fall back to a text input for that field.
 *
 * HEADQUARTERS: the 182 entries the console offered on 2026-10-08, "United
 * States of America" and "Canada" first, then alphabetical from
 * "Afghanistan", exactly as logged by the questionnaire handler (it logs
 * every option list it opens: `select "headquarters" offers N options:
 * ...`). The console lists "Congo" twice; both entries are kept so the list
 * is the console's. When the console changes its list, refill this array
 * from a fresh log.
 *
 * Loaded by a <script> tag in the options page only.
 */
(function () {
  if (globalThis.MGC_OPTIONS) return;
  const O = {};

  O.OTHER = "Other (type the exact console option)";

  O.HEADQUARTERS = [
    "United States of America",
    "Canada",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burma/Myanmar",
    "Cabo Verde",
    "Central African Republic",
    "Chile",
    "China (including Hong Kong and Macau)",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia (Czech Republic)",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See (Vatican City)",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tanzania",
    "Thailand",
    "Timor-Leste, Democratic Republic of",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Tuvalu",
    "Uganda",
    "Ukraine (Crimea, Donetsk, and Luhansk regions)",
    "Ukraine (except Crimea, Donetsk, and Luhansk regions)",
    "United Arab Emirates",
    "United Kingdom",
    "Uruguay",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ];

  O.INDUSTRY = [
    "Agriculture",
    "Customer service",
    "Education",
    "Energy",
    "Financial services",
    "Gaming",
    "Government",
    "Healthcare",
    "Human resources",
    "Legal",
    "Manufacturing",
    "Media and entertainment",
    "Retail",
    "Supply chain and logistics",
    "Telecommunications",
    "Transportation"
  ];

  O.INTENDED_USERS = [
    "Internal employees",
    "external customer or users",
    "Internal employees and external users"
  ];

  /* setting key -> list */
  O.BY_FIELD = {
    headquarters: O.HEADQUARTERS,
    industry: O.INDUSTRY,
    intended_users: O.INTENDED_USERS
  };

  globalThis.MGC_OPTIONS = O;
})();
